# Makefile for linuxtv.org dvb-apps/lib/libdvbcfg

includes = dvbcfg_sec.h        \
           dvbcfg_zapchannel.h

objects  = dvbcfg_sec.o        \
           dvbcfg_utils.o      \
           dvbcfg_zapchannel.o

lib_name = libdvbcfg

CPPFLAGS += -I../../lib

.PHONY: all

all: library

include ../../Make.rules
