# Makefile for linuxtv.org dvb-apps/util

all %::
	$(MAKE) -C szap $(MAKECMDGOALS)
	$(MAKE) -C scan $(MAKECMDGOALS)
	$(MAKE) -C ca_zap $(MAKECMDGOALS)
	$(MAKE) -C dvbnet $(MAKECMDGOALS)
	$(MAKE) -C dvbdate $(MAKECMDGOALS)
	$(MAKE) -C dvbtraffic $(MAKECMDGOALS)
	$(MAKE) -C av7110_loadkeys $(MAKECMDGOALS)
	$(MAKE) -C ttusb_dec_reset $(MAKECMDGOALS)
	$(MAKE) -C dst-utils $(MAKECMDGOALS)
