
.PHONY: libdvbapi libdvbcfg libucsi libdvben50221

all:

%::
	$(MAKE) -C libdvbapi $(MAKECMDGOALS)
	$(MAKE) -C libdvbcfg $(MAKECMDGOALS)
	$(MAKE) -C libucsi $(MAKECMDGOALS)
	$(MAKE) -C libdvben50221 $(MAKECMDGOALS)
